import manifest from "./media-manifest.json";

export type Photo = {
  id: string;
  aspect: number;
  lqip: string;
  full: string;
  fullJpg: string;
  card: string;
  cardJpg: string;
  thumb: string;
};

// Generated by scripts/optimize-media.mjs. Empty until that script runs.
export const PHOTOS: Photo[] = manifest as Photo[];

// Safe accessor — returns a photo by index, wrapping around, or undefined.
export const photo = (i: number): Photo | undefined =>
  PHOTOS.length ? PHOTOS[i % PHOTOS.length] : undefined;

export const SLOGANS = {
  hero: "Faster. Better. Siegfried 2.0.",
  sim: "Innovation meets simulation.",
  openSource: "Open-source automotive intelligence.",
  future: "Built for the future.",
};

export const GITHUB_URL = "https://github.com/Matteo-Super/Siegfried-2.0";

export const NAV_LINKS = [
  { label: "Features", href: "#features" },
  { label: "Simulator", href: "#simulator" },
  { label: "Galerie", href: "#showcase" },
  { label: "Preise", href: "#pricing" },
  { label: "Open Source", href: "#opensource" },
];

export type Feature = {
  icon: string;
  title: string;
  desc: string;
};

export const FEATURES: Feature[] = [
  {
    icon: "fa-solid fa-microchip",
    title: "Arduino-Kern",
    desc: "ATmega-Mikrocontroller als Herzstück. Vollständig programmierbar über die Arduino IDE — kein Vendor-Lock-in.",
  },
  {
    icon: "fa-solid fa-satellite-dish",
    title: "HC-SR04 Ultraschall",
    desc: "Präzise Entfernungsmessung bis 2,2 m. Echtzeit-Hinderniserkennung mit servogesteuertem Scan-Schwenk.",
  },
  {
    icon: "fa-solid fa-route",
    title: "Linien-Tracking",
    desc: "Drei Infrarotsensoren folgen Linien millimetergenau und schalten autonom in den Ausweich-Modus.",
  },
  {
    icon: "fa-solid fa-rainbow",
    title: "WS2812 RGB-Strip",
    desc: "10 adressierbare LEDs visualisieren Status, Geschwindigkeit und Sensorlage in Echtzeit.",
  },
  {
    icon: "fa-solid fa-car-burst",
    title: "Befreiungs-Logik",
    desc: "Erkennt Festfahren und löst eine intelligente Befreiungs-Sequenz aus — Siegfried gibt nie auf.",
  },
  {
    icon: "fa-solid fa-code-branch",
    title: "100% Open Source",
    desc: "Firmware, Schaltpläne und CAD frei verfügbar. Forken, anpassen, beitragen — alles offen.",
  },
];

export type Spec = { label: string; value: string };

export const KIT_INCLUDES: string[] = [
  "4WD Chassis mit Getriebemotoren",
  "Arduino-kompatibles Mainboard + USB-Kabel",
  "Dual-H-Brücken Motortreiber",
  "HC-SR04 Ultraschall + Servo-Schwenkkopf",
  "3× Infrarot Linien-Sensoren",
  "WS2812B RGB-LED-Strip (10 LEDs)",
  "Akkus + Halterung",
  "Vollständige Open-Source-Firmware",
];

// Stripe tip presets (amount in EUR). Each maps to a payment link in stripe.ts.
export const TIP_PRESETS = [1, 3, 5, 10] as const;

// Curated photo indices (0-based into PHOTOS) chosen from the contact sheet for
// their composition/lighting. Falls back gracefully if the manifest is shorter.
export const CURATED = {
  hero: 15, // photo-16 — dramatic red underglow on dark
  product: 9, // photo-10 — clear full car, battery visible
  showcase: [17, 8, 22, 10], // red front, blue dark, blue side, purple
  gallery: [15, 17, 8, 22, 10, 13, 1, 18, 28, 25, 12, 6],
};
